version: '2'
services:
  #topics:
  #  container_name: topics
  #  build:
  #    context: .
  #  image: jaycecordon/vltopics:0.0.1-SNAPSHOT
  #  ports:
  #    - "8641:8641"

  db-campaign:
    image: postgres:alpine
    ports:
      - '8742:5432'
    container_name: dbcampaign
    environment:
      POSTGRES_DB: db_VL-campaign
      POSTGRES_USER: usr_campaign
      POSTGRES_PASSWORD: campaign
    volumes:
      - './sql:/docker-entrypoint-initdb.d'
    restart: always
    network_mode: bridge
